const usArmyRanks = [
  { slug: "private_noimage", name: "Private (E-1)" },
  { slug: "private", name: "Private (E-2)" },
  { slug: "private_first_class", name: "Private First Class (E-3)" },
  { slug: "specialist", name: "Specialist (E-4)" },
  { slug: "corporal", name: "Corporal (E-4)" },
  { slug: "sergeant", name: "Sergeant (E-5)" },
  { slug: "staff_sergeant", name: "Staff Sergeant (E-6)" },
  { slug: "sergeant_first_class", name: "Sergeant First Class (E-7)" },
  { slug: "master_sergeant", name: "Master Sergeant (E-8)" },
  { slug: "first_sergeant", name: "First Sergeant (E-8)" },
  { slug: "sergeant_major", name: "Sergeant Major (E-9)" },
  { slug: "command_sergeant_major", name: "Command Sergeant Major (E-9)" },
  { slug: "sergeant_major_of_the_army", name: "Sergeant Major of the Army" },
  { slug: "cw1", name: "Warrant Officer 1 (W-1)" },
  { slug: "cw2", name: "Chief Warrant Officer 2 (W-2)" },
  { slug: "cw3", name: "Chief Warrant Officer 3 (W-3)" },
  { slug: "cw4", name: "Chief Warrant Officer 4 (W-4)" },
  { slug: "cw5", name: "Chief Warrant Officer 5 (W-5)" },
  { slug: "second_lieutenant", name: "Second Lieutenant (O-1)" },
  { slug: "first_lieutenant", name: "First Lieutenant (O-2)" },
  { slug: "captain", name: "Captain (O-3)" },
  { slug: "major", name: "Major (O-4)" },
  { slug: "lieutenant_colonel", name: "Lieutenant Colonel (O-5)" },
  { slug: "colonel", name: "Colonel (O-6)" },
  { slug: "brigadier_general", name: "Brigadier General (O-7)" },
  { slug: "major_general", name: "Major General (O-8)" },
  { slug: "lieutenant_general", name: "Lieutenant General (O-9)" },
  { slug: "general", name: "General (O-10)" },
  { slug: "general_of_the_army", name: "General of the Army" },
];

export default usArmyRanks;
