const quizData = [
  { countryCode: "US", country: "United States", capital: "Washington, D.C." },
  { countryCode: "CA", country: "Canada", capital: "Ottawa" },
  { countryCode: "MX", country: "Mexico", capital: "Mexico City" },
  { countryCode: "BR", country: "Brazil", capital: "Brasilia" },
  { countryCode: "AR", country: "Argentina", capital: "Buenos Aires" },
  { countryCode: "CL", country: "Chile", capital: "Santiago" },
  { countryCode: "CO", country: "Colombia", capital: "Bogota" },
  { countryCode: "PE", country: "Peru", capital: "Lima" },
  { countryCode: "GB", country: "United Kingdom", capital: "London" },
  { countryCode: "IE", country: "Ireland", capital: "Dublin" },
  { countryCode: "FR", country: "France", capital: "Paris" },
  { countryCode: "DE", country: "Germany", capital: "Berlin" },
  { countryCode: "IT", country: "Italy", capital: "Rome" },
  { countryCode: "ES", country: "Spain", capital: "Madrid" },
  { countryCode: "PT", country: "Portugal", capital: "Lisbon" },
  { countryCode: "NL", country: "Netherlands", capital: "Amsterdam" },
  { countryCode: "BE", country: "Belgium", capital: "Brussels" },
  { countryCode: "CH", country: "Switzerland", capital: "Bern" },
  { countryCode: "AT", country: "Austria", capital: "Vienna" },
  { countryCode: "SE", country: "Sweden", capital: "Stockholm" },
  { countryCode: "NO", country: "Norway", capital: "Oslo" },
  { countryCode: "DK", country: "Denmark", capital: "Copenhagen" },
  { countryCode: "FI", country: "Finland", capital: "Helsinki" },
  { countryCode: "PL", country: "Poland", capital: "Warsaw" },
  { countryCode: "CZ", country: "Czech Republic", capital: "Prague" },
  { countryCode: "GR", country: "Greece", capital: "Athens" },
  { countryCode: "TR", country: "Turkey", capital: "Ankara" },
  { countryCode: "UA", country: "Ukraine", capital: "Kyiv" },
  { countryCode: "RU", country: "Russia", capital: "Moscow" },
  { countryCode: "EG", country: "Egypt", capital: "Cairo" },
  { countryCode: "ZA", country: "South Africa", capital: "Pretoria" },
  { countryCode: "NG", country: "Nigeria", capital: "Abuja" },
  { countryCode: "KE", country: "Kenya", capital: "Nairobi" },
  { countryCode: "MA", country: "Morocco", capital: "Rabat" },
  { countryCode: "SA", country: "Saudi Arabia", capital: "Riyadh" },
  { countryCode: "IL", country: "Israel", capital: "Jerusalem" },
  { countryCode: "AE", country: "United Arab Emirates", capital: "Abu Dhabi" },
  { countryCode: "IN", country: "India", capital: "New Delhi" },
  { countryCode: "PK", country: "Pakistan", capital: "Islamabad" },
  { countryCode: "BD", country: "Bangladesh", capital: "Dhaka" },
  { countryCode: "TH", country: "Thailand", capital: "Bangkok" },
  { countryCode: "VN", country: "Vietnam", capital: "Hanoi" },
  { countryCode: "MY", country: "Malaysia", capital: "Kuala Lumpur" },
  { countryCode: "SG", country: "Singapore", capital: "Singapore" },
  { countryCode: "ID", country: "Indonesia", capital: "Jakarta" },
  { countryCode: "PH", country: "Philippines", capital: "Manila" },
  { countryCode: "CN", country: "China", capital: "Beijing" },
  { countryCode: "JP", country: "Japan", capital: "Tokyo" },
  { countryCode: "KR", country: "South Korea", capital: "Seoul" },
  { countryCode: "AU", country: "Australia", capital: "Canberra" },
  { countryCode: "NZ", country: "New Zealand", capital: "Wellington" },
];

export default quizData;
