import App from "@/components/Page";
import { Metadata } from "next";
import FlightCO2Calculator from "./co2Calculator";
import Info from "./info.mdx";

export default function FlightCarbonFootprintCalculator() {
  return (
    <App {...pageProps}>
      <FlightCO2Calculator />
    </App>
  );
}

const pageProps = {
  seoTitle:
    "Flight Carbon Footprint Calculator - Easily Calculate Flight CO2 Emissions",
  title: "Flight Carbon Footprint Calculator",
  description:
    "Easily calculate the carbon footprint of your flight journey with the flight carbon footprint calculator. Enter your departure and destination cities, and get an accurate estimate of the carbon dioxide emissions generated by your flight. Understand the environmental impact of flying and make responsible travel choices.",
  instructions:
    "Use the flight carbon footprint calculator to determine the environmental impact of your flight journey. Enter the information of the departure and destination airport cities, and the calculator will provide you with an accurate estimate of the flight's carbon dioxide emissions. This way, you can understand the environmental impacts of flying and make more responsible travel choices.",
  Info,
};

export const metadata: Metadata = {
  title: pageProps.seoTitle,
  description: pageProps.description,
};
