const quizData = [
  { code: "AL", state: "Alabama", capital: "Montgomery" },
  { code: "AK", state: "Alaska", capital: "Juneau" },
  { code: "AZ", state: "Arizona", capital: "Phoenix" },
  { code: "AR", state: "Arkansas", capital: "Little Rock" },
  { code: "CA", state: "California", capital: "Sacramento" },
  { code: "CO", state: "Colorado", capital: "Denver" },
  { code: "CT", state: "Connecticut", capital: "Hartford" },
  { code: "DE", state: "Delaware", capital: "Dover" },
  { code: "FL", state: "Florida", capital: "Tallahassee" },
  { code: "GA", state: "Georgia", capital: "Atlanta" },
  { code: "HI", state: "Hawaii", capital: "Honolulu" },
  { code: "ID", state: "Idaho", capital: "Boise" },
  { code: "IL", state: "Illinois", capital: "Springfield" },
  { code: "IN", state: "Indiana", capital: "Indianapolis" },
  { code: "IA", state: "Iowa", capital: "Des Moines" },
  { code: "KS", state: "Kansas", capital: "Topeka" },
  { code: "KY", state: "Kentucky", capital: "Frankfort" },
  { code: "LA", state: "Louisiana", capital: "Baton Rouge" },
  { code: "ME", state: "Maine", capital: "Augusta" },
  { code: "MD", state: "Maryland", capital: "Annapolis" },
  { code: "MA", state: "Massachusetts", capital: "Boston" },
  { code: "MI", state: "Michigan", capital: "Lansing" },
  { code: "MN", state: "Minnesota", capital: "Saint Paul" },
  { code: "MS", state: "Mississippi", capital: "Jackson" },
  { code: "MO", state: "Missouri", capital: "Jefferson City" },
  { code: "MT", state: "Montana", capital: "Helena" },
  { code: "NE", state: "Nebraska", capital: "Lincoln" },
  { code: "NV", state: "Nevada", capital: "Carson City" },
  { code: "NH", state: "New Hampshire", capital: "Concord" },
  { code: "NJ", state: "New Jersey", capital: "Trenton" },
  { code: "NM", state: "New Mexico", capital: "Santa Fe" },
  { code: "NY", state: "New York", capital: "Albany" },
  { code: "NC", state: "North Carolina", capital: "Raleigh" },
  { code: "ND", state: "North Dakota", capital: "Bismarck" },
  { code: "OH", state: "Ohio", capital: "Columbus" },
  { code: "OK", state: "Oklahoma", capital: "Oklahoma City" },
  { code: "OR", state: "Oregon", capital: "Salem" },
  { code: "PA", state: "Pennsylvania", capital: "Harrisburg" },
  { code: "RI", state: "Rhode Island", capital: "Providence" },
  { code: "SC", state: "South Carolina", capital: "Columbia" },
  { code: "SD", state: "South Dakota", capital: "Pierre" },
  { code: "TN", state: "Tennessee", capital: "Nashville" },
  { code: "TX", state: "Texas", capital: "Austin" },
  { code: "UT", state: "Utah", capital: "Salt Lake City" },
  { code: "VT", state: "Vermont", capital: "Montpelier" },
  { code: "VA", state: "Virginia", capital: "Richmond" },
  { code: "WA", state: "Washington", capital: "Olympia" },
  { code: "WV", state: "West Virginia", capital: "Charleston" },
  { code: "WI", state: "Wisconsin", capital: "Madison" },
  { code: "WY", state: "Wyoming", capital: "Cheyenne" },
];

export default quizData;
